In [1]:
import numpy as np

In [4]:
M = np.ones((3,3),dtype=np.int32)

In [29]:
Q = 2*np.identity(3) - M 

In [30]:
Q

array([[ 1., -1., -1.],
       [-1.,  1., -1.],
       [-1., -1.,  1.]])

In [47]:
ee, vv = np.linalg.eig(Q)

np.dot(vv.transpose(), vv).astype(int)


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [49]:
vv[:,1]

array([ 0.81649658, -0.40824829, -0.40824829])

In [33]:
np.dot(Q, np.ones(3))

array([-1., -1., -1.])

In [34]:
np.linalg.norm(vv[:, 0])

1.0

In [57]:
k = 2
vv[:, k]/min(abs(vv[:, k]))

array([ 1., -2.,  1.])

In [36]:
np.dot(Q, vx)

array([-1., -1., -1.])

In [25]:
ee

array([ 3., -3.,  3.])

In [37]:
np.linalg.norm(vx)**2

3.0000000000000004